import './globals.css'

import { Providers } from '@/shared/providers/providers'
import AppToaster from '@/shared/ui/app-toaster'
import ClientOnlyWrapper from '@/shared/ui/client-only-wrapper'
import { Geist, Geist_Mono } from 'next/font/google'
import type { Metadata } from 'next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <ClientOnlyWrapper />
          <AppToaster />
          {children}
        </Providers>
      </body>
    </html>
  )
}
